// users
export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_PROFILE_TO_DATE = 'ADD_PROFILE_TO_DATE';
export const ADD_DATE_TO_PROFILE = 'ADD_DATE_TO_PROFILE';
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
export const SET_USER_COORDS = 'SET_USER_COORDS';

// errors
export const GENERIC_ERROR = 'GENERIC_ERROR';
