// title
export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_PROFILE_TO_DATE = 'ADD_PROFILE_TO_DATE';
export const ADD_DATE_TO_PROFILE = 'ADD_DATE_TO_PROFILE';
export const SENDING_LOGIN_REQUEST = 'SENDING_LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

// errors
export const GENERIC_ERROR = 'GENERIC_ERROR';
