const constants = {
  ADD_PROFILE: 'ADD_PROFILE',
  ADD_PROFILE_TO_DATE: 'ADD_PROFILE_TO_DATE',
  ADD_DATE_TO_PROFILE: 'ADD_DATE_TO_PROFILE',
  SENDING_LOGIN_REQUEST: 'SENDING_LOGIN_REQUEST',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_FAILURE: 'LOGIN_REQUEST_FAILURE',


  ADD_DAY: 'ADD_DAY',
  REMOVE_DAY: 'REMOVE_DAY',
  SET_GOAL: 'SET_GOAL',
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  FETCH_RESORT_NAMES: 'FETCH_RESORT_NAMES',
  CANCEL_FETCHING: 'CANCEL_FETCHING',
  CHANGE_SUGGESTIONS: 'CHANGE_SUGGESTIONS',
  CLEAR_SUGGESTIONS: 'CLEAR_SUGGESTIONS'
};

export default constants;
